### ISSUE TITLE
[Config] SwiftLint 세팅 

### ISSUE THREAD

**Issue by jane1choi** [dnd-side-project/dnd-10th-10-iOS#7]
## 🚀 Feature Issue
- 코드 스타일 통일 및 컨벤션 유지에 용이하도록 SwiftLint를 세팅합니다. 

## 📝 To-do
- [x] SwiftLint 설치
- [x] rule 추가

**Comment by sunny5875** [comment]
빌드 잘 되는 거 확인했습니다! 그대로 머지하시면 될 거 같아용 🥳
